name: log_service
description: A Dart package for simplify the usage of the official `logging` package.
version: 1.0.0
repository: https://github.com/yanshouwang/log_service

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: ^1.2.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
